### ISSUE TITLE
mgutils.js path  command use in graph construction

### ISSUE THREAD

**Issue by wushyer** [mb47/minigraph-barley#1]
Hi, I tried to run the pipeline but encountered one issue, code listed below. I didn't find any minigraph version with mgutils.js run a path subcommand. Could you please check this issue? Thanks.

> paste *.call.bed \
> | mgutils.js path pathPrefixes.$chrom.txt - \
> > $chrom.paths.mgutils.gfa

Best,
Shuangyang

**Comment by mb47** [comment]
Hi Shuangyang,

sorry about that -- I just had a look at this. The addition of the path command to this minigraph script was suggested in a pull request in 2022 (https://github.com/lh3/minigraph/pull/77) but from what I can tell this hasn't been merged into the master. 

I must have manually downloaded the modified version of the script from the pull request and then added it locally to my PATH. I'd suggest you do the same -- see https://github.com/lh3/minigraph/pull/77/files.

best
Micha

**Comment by wushyer** [comment]
Thanks Micha.

I downloaded this version and tried the command, but encountered the error below. Do you have any insights into this issue? Thank you!

_paste *.call.bed|k8 /scratch-cbe/users/shuangyang.wu/huaishu-9/minigraph-barley/scripts/graphConstruction/minigraph/misc/mgutils.js path pathPrefixes.Chr04.txt - > test.gfa
/scratch-cbe/users/shuangyang.wu/huaishu-9/minigraph-barley/scripts/graphConstruction/minigraph/misc/mgutils.js:1403: TypeError: Cannot read property 'length' of undefined
            if (!paths[index].length) {
                             ^
TypeError: Cannot read property 'length' of undefined
    at mg_cmd_path (/scratch-cbe/users/shuangyang.wu/huaishu-9/minigraph-barley/scripts/graphConstruction/minigraph/misc/mgutils.js:1403:30)
    at main (/scratch-cbe/users/shuangyang.wu/huaishu-9/minigraph-barley/scripts/graphConstruction/minigraph/misc/mgutils.js:1477:26)
    at /scratch-cbe/users/shuangyang.wu/huaishu-9/minigraph-barley/scripts/graphConstruction/minigraph/misc/mgutils.js:1483:1_

**Comment by ASLeonard** [comment]
Re-pathing a minigraph pangenome is pretty useful but definitely broken in many locations where `minigraph --call` couldn't make a judgement. There were also some changes in k8 and I tried rewriting the invalid path lines to use J-lines (to work with the latest BandageNG) but that seemed to break other tools. Using commit 38f0459 should at least work with the originally intended behaviour.
